spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:inkatrackertest;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    schema: classpath:database/functions/mysql_custom_h2_functions.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        dialect: org.hibernate.dialect.H2Dialect
    database: h2

task:
  insink:
    ordersFetchInterval: 10000000
  webhook:
      failedRetryInterval: 10000000
  group:
    groupOffersInterval: 50000000

external:
  mapi:
    drugstore:
      geturl: https://qurswintke.execute-api.us-west-2.amazonaws.com/CI/drugstores
    client:
      url: https://qurswintke.execute-api.us-west-2.amazonaws.com/CI/client
  firebase:
    config: classpath:security/ci/FirebaseServiceAccount.json
    database: https://inkafarma-ci.firebaseio.com/
    notification:
      user: 267864932212@gcm.googleapis.com
      password: AAAAPl3-f3Q:APA91bHGd-0suR4hP1j_RR9hwPZtBkcHRmzkBPjaV2RYmrxIPW2KMygcCuWb2mqpZf0muVqwY4DEeya9IwpYIuq3KTku6BrcEMiRGDVFYNa5bTaKEcIempRCl64cH7b6XgNR467oagT_
      maxRetries: 5
      protocol: https
      host: fcm.googleapis.com/fcm
      services:
        send: /send
  insink:
    connectTimeout: 15000
    readTimeout: 40000
    protocol: http
    host: localhost:8383
    services:
      orders: /orders?localIds={localIds}&lastEvaluatedDate={lastEvaluatedDate}&evaluatedOrderIds={evaluatedOrderIds}
  google:
      protocol: https
      host: maps.googleapis.com
      key: AIzaSyDZ-KFhTwz5GQsl7LQRnEAVXM8i1OhuNuo
      geocode:
        url: /maps/api/geocode/json
      distance:
        url: /maps/api/distancematrix/json
flyway:
  locations: classpath:database
logging:
  level:
    com.globant.inkafarma: DEBUG
globant:
  system:
    firebase:
      service-account: classpath:security/ci/FirebaseServiceAccount.json
      database-url: https://inkafarma-ci.firebaseio.com/
    security:
      disabled-for:
        - /dd/**

order:
  status:
    rules:
      security-permission-id: 1
      message-if-can-not-change-status: No tienes el permiso para realizar el cambio
      rule-by-status:
        INGRESADA:
          required-assign: false
        EN TIENDA:
          required-assign: false
          message-if-not-present: Es necesario ingresar la botica a asignar
          validator-class: com.inkafarma.tracker.rest.validator.DrugstoreValidator
          assign-rule:
            type: drugstore
            message-if-not-available: La botica no existe o no se encuentra activa
        PREPARADA:
          required-assign: false
          message-if-not-present: Es necesario ingresar la botica a asignar
          validator-class: com.inkafarma.tracker.rest.validator.DrugstoreValidator
          assign-rule:
            type: drugstore
            message-if-not-available: La botica no existe o no se encuentra activa
        DESPACHADA:
          required-assign: true
          message-if-not-present: Es necesario ingresar el motorizado a asignar
          validator-class: com.inkafarma.tracker.rest.validator.TrackerUserValidator
          assign-rule:
            type: tracker-user
            role: ROLE_MOTORIZADO
            message-if-not-available: El motorizado no existe o no se encuentra activo
            message-if-not-in-role: El usuario asignado no es motorizado
        EN CAMINO:
          required-assign: false
          message-if-not-present: Es necesario ingresar el motorizado a asignar
          required-time-and-gps: true
          message-if-time-gps-not-present: Los datos de hora y gps son necesarios
          assign-rule:
            type: tracker-user
            role: ROLE_MOTORIZADO
            message-if-not-available: El motorizado no existe o no se encuentra activo
            message-if-not-in-role: El usuario asignado no es motorizado
        TENGO LA TRANSFERENCIA:
          required-assign: false
          required-time-and-gps: true
          message-if-time-gps-not-present: Los datos de hora y gps son necesarios
        TRANSFERIDA:
          required-assign: false
          required-time-and-gps: false
        CANCELADA:
          required-assign: false
        LLEGO:
          required-time-and-gps: true
          message-if-time-gps-not-present: Los datos de hora y gps son necesarios
        ENTREGADA:
          required-time-and-gps: true
          message-if-time-gps-not-present: Los datos de hora y gps son necesarios
        RECHAZADA:
          required-time-and-gps: true
          message-if-time-gps-not-present: Los datos de hora y gps son necesarios
